"""added time created and character limits

Revision ID: e4873532adee
Revises: 8540aa380222
Create Date: 2024-10-09 04:53:14.197628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4873532adee'
down_revision = '8540aa380222'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('time_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'time_created')
    # ### end Alembic commands ###
